// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",      
  options: {
    checkForUpdate: false
  },
  handlers: [
    {
      // Open google.com and *.google.com urls in Google Chrome
      match: [
	"youtube.com",
	"youtube.com/*",
        "*.google.com/*", // match google.com subdomains
        "*.google.com", // match google.com subdomains
      ],
      browser: "/Applications/Min.app"
    }
  ]
}
